// ============================================================================
// Construction Module - Mock Data
// Red Cedar Homes ATLAS Platform
// ============================================================================

import type {
  Job,
  Unit,
  Milestone,
  PurchaseOrder,
  ChangeOrder,
  Inspection,
  Selection,
  Vendor,
  WarrantyClaim,
  ActivityFeedItem,
} from "./types"
import { CONSTRUCTION_PHASES, PHASE_INSPECTIONS } from "./types"

// ---- Jobs ----
export const MOCK_JOBS: Job[] = [
  {
    id: "job-001",
    job_number: "RCH-2025-001",
    name: "Millbrook Crossing Phase 2",
    client_type: "internal",
    client_entity: "Red Cedar Homes SC, LLC",
    contract_type: "cost_plus",
    contract_amount: 8750000,
    builder_fee: 612500,
    unit_count: 24,
    units_completed: 6,
    linked_project_id: "proj-001",
    state: "SC",
    superintendent: "Mike Thompson",
    project_manager: "Sarah Chen",
    start_date: "2025-03-15",
    projected_completion: "2026-09-30",
    status: "active",
    created_at: "2025-02-01T10:00:00Z",
    updated_at: "2026-02-15T14:30:00Z",
  },
  {
    id: "job-002",
    job_number: "RCH-2025-002",
    name: "Oakridge Estates Lot 14-18",
    client_type: "third_party",
    client_name: "Palmetto Land Group",
    contract_type: "fixed_price",
    contract_amount: 2250000,
    builder_fee: 225000,
    unit_count: 5,
    units_completed: 2,
    state: "SC",
    superintendent: "Dave Rodriguez",
    project_manager: "Sarah Chen",
    start_date: "2025-06-01",
    projected_completion: "2026-04-15",
    status: "active",
    created_at: "2025-05-10T08:00:00Z",
    updated_at: "2026-02-10T09:00:00Z",
  },
  {
    id: "job-003",
    job_number: "RCH-2025-003",
    name: "River Bend Townhomes",
    client_type: "internal",
    client_entity: "Red Cedar Homes NC, LLC",
    contract_type: "cost_plus",
    contract_amount: 4200000,
    builder_fee: 294000,
    unit_count: 12,
    units_completed: 0,
    linked_project_id: "proj-003",
    state: "NC",
    superintendent: "Jim Patterson",
    project_manager: "Maria Gonzalez",
    start_date: "2025-11-01",
    projected_completion: "2026-12-31",
    status: "preconstruction",
    created_at: "2025-10-01T10:00:00Z",
    updated_at: "2026-02-01T11:00:00Z",
  },
  {
    id: "job-004",
    job_number: "RCH-2024-008",
    name: "Winding Creek Single-Family",
    client_type: "internal",
    client_entity: "Red Cedar Homes SC, LLC",
    contract_type: "cost_plus",
    contract_amount: 5800000,
    builder_fee: 406000,
    unit_count: 16,
    units_completed: 16,
    linked_project_id: "proj-004",
    state: "SC",
    superintendent: "Mike Thompson",
    project_manager: "Sarah Chen",
    start_date: "2024-06-01",
    projected_completion: "2025-12-31",
    status: "completed",
    created_at: "2024-05-01T10:00:00Z",
    updated_at: "2025-12-20T15:00:00Z",
  },
  {
    id: "job-005",
    job_number: "RCH-2025-005",
    name: "Magnolia Row Custom Homes",
    client_type: "third_party",
    client_name: "Coastal Development Partners",
    contract_type: "time_materials",
    contract_amount: 3100000,
    builder_fee: 310000,
    unit_count: 8,
    units_completed: 1,
    state: "NC",
    superintendent: "Jim Patterson",
    project_manager: "Maria Gonzalez",
    start_date: "2025-08-15",
    projected_completion: "2026-08-15",
    status: "active",
    created_at: "2025-07-20T10:00:00Z",
    updated_at: "2026-02-12T16:00:00Z",
  },
]

// ---- Units for Job 001 (Millbrook Crossing Phase 2) ----
function generateUnitsForJob001(): Unit[] {
  const plans = [
    { name: "The Ashford", specs: "4BR/3BA, 2,450 SF", budget: 365000 },
    { name: "The Beaumont", specs: "3BR/2.5BA, 2,100 SF", budget: 325000 },
    { name: "The Crestview", specs: "4BR/3.5BA, 2,800 SF", budget: 410000 },
    { name: "The Dunmore", specs: "3BR/2BA, 1,850 SF", budget: 295000 },
  ]

  return Array.from({ length: 24 }, (_, i) => {
    const num = i + 1
    const plan = plans[i % plans.length]
    const phase = num <= 6 ? 16 : num <= 12 ? 9 + Math.floor((num - 6) / 2) : num <= 18 ? 4 + Math.floor((num - 12) / 2) : 1 + Math.floor((num - 18) / 3)
    const isComplete = num <= 6
    const isNotStarted = num > 20

    let scheduleStatus: Unit["schedule_status"] = "on_schedule"
    if (isComplete) scheduleStatus = "complete"
    else if (isNotStarted) scheduleStatus = "not_started"
    else if (num === 8 || num === 14) scheduleStatus = "behind_1_7"
    else if (num === 10) scheduleStatus = "behind_8_plus"

    const committed = isComplete ? plan.budget * 0.98 : plan.budget * (phase / 16) * 0.85
    const actual = isComplete ? plan.budget * 0.96 : committed * 0.9

    return {
      id: `unit-001-${String(num).padStart(3, "0")}`,
      job_id: "job-001",
      unit_number: `MC2-${String(num).padStart(3, "0")}`,
      address: `${100 + num} Millbrook Crossing Dr, Greenville, SC 29607`,
      floor_plan_name: plan.name,
      floor_plan_specs: plan.specs,
      upgrade_package: num % 3 === 0 ? "Premium Plus" : num % 2 === 0 ? "Standard Upgrade" : undefined,
      current_phase: isComplete ? 16 : isNotStarted ? 0 : phase,
      permit_date: isNotStarted ? undefined : "2025-04-10",
      construction_start: isNotStarted ? undefined : "2025-05-01",
      projected_completion: isNotStarted ? undefined : isComplete ? "2025-12-15" : "2026-06-30",
      co_date: isComplete ? "2025-12-10" : undefined,
      total_budget: plan.budget,
      committed: Math.round(committed),
      actual: Math.round(actual),
      status: isComplete ? "complete" : isNotStarted ? "not_started" : "in_progress",
      schedule_status: scheduleStatus,
      created_at: "2025-03-15T10:00:00Z",
    }
  })
}

export const MOCK_UNITS_JOB001 = generateUnitsForJob001()

// ---- Milestones for a specific unit (MC2-007, in-progress at phase 10) ----
export function generateMilestones(unitId: string, currentPhase: number): Milestone[] {
  const baseDate = new Date("2025-05-01")
  return CONSTRUCTION_PHASES.map((phase) => {
    const plannedStart = new Date(baseDate)
    plannedStart.setDate(baseDate.getDate() + (phase.number - 1) * 14)
    const plannedEnd = new Date(plannedStart)
    plannedEnd.setDate(plannedStart.getDate() + 12)

    let status: Milestone["status"] = "not_started"
    let actualStart: string | undefined
    let actualEnd: string | undefined
    let actualDuration: number | undefined

    if (phase.number < currentPhase) {
      status = "completed"
      const aStart = new Date(plannedStart)
      aStart.setDate(aStart.getDate() + Math.floor(Math.random() * 3) - 1)
      actualStart = aStart.toISOString().split("T")[0]
      const aEnd = new Date(plannedEnd)
      aEnd.setDate(aEnd.getDate() + Math.floor(Math.random() * 5) - 2)
      actualEnd = aEnd.toISOString().split("T")[0]
      actualDuration = Math.round(
        (new Date(actualEnd).getTime() - new Date(actualStart).getTime()) /
          (1000 * 60 * 60 * 24)
      )
    } else if (phase.number === currentPhase) {
      status = "in_progress"
      const aStart = new Date(plannedStart)
      aStart.setDate(aStart.getDate() + 1)
      actualStart = aStart.toISOString().split("T")[0]
    }

    const requiredInspections = PHASE_INSPECTIONS[phase.number] || []
    const inspections: Inspection[] = requiredInspections.map((type, idx) => ({
      id: `insp-${unitId}-${phase.number}-${idx}`,
      unit_id: unitId,
      milestone_id: `ms-${unitId}-${phase.number}`,
      phase_number: phase.number,
      type,
      scheduled_date: plannedEnd.toISOString().split("T")[0],
      actual_date:
        phase.number < currentPhase
          ? plannedEnd.toISOString().split("T")[0]
          : undefined,
      result: phase.number < currentPhase ? "pass" : undefined,
      inspector: phase.number < currentPhase ? "Greenville County" : undefined,
      municipality: "Greenville County",
      notes: undefined,
      is_required: true,
      is_reinspection: false,
    }))

    return {
      id: `ms-${unitId}-${phase.number}`,
      unit_id: unitId,
      phase_number: phase.number,
      phase_name: phase.name,
      status,
      planned_start: plannedStart.toISOString().split("T")[0],
      planned_end: plannedEnd.toISOString().split("T")[0],
      actual_start: actualStart,
      actual_end: actualEnd,
      planned_duration: 12,
      actual_duration: actualDuration,
      inspections,
    }
  })
}

// ---- Purchase Orders ----
export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po-001",
    po_number: "PO-2025-0147",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Framing - Lumber Material",
    vendor_name: "Carolina Lumber Supply",
    description: "Framing lumber package - The Beaumont plan",
    amount: 28500,
    retainage_percent: 5,
    retainage_amount: 1425,
    net_amount: 27075,
    status: "paid",
    lien_waiver_status: "final",
    created_at: "2025-06-15T10:00:00Z",
  },
  {
    id: "po-002",
    po_number: "PO-2025-0148",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Framing - Labor",
    vendor_name: "Precision Framing LLC",
    description: "Framing labor - complete rough framing",
    amount: 18200,
    retainage_percent: 5,
    retainage_amount: 910,
    net_amount: 17290,
    status: "paid",
    lien_waiver_status: "final",
    created_at: "2025-06-20T10:00:00Z",
  },
  {
    id: "po-003",
    po_number: "PO-2025-0165",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Roofing",
    vendor_name: "Summit Roofing Co",
    description: "Architectural shingle roof - complete install",
    amount: 12800,
    retainage_percent: 5,
    retainage_amount: 640,
    net_amount: 12160,
    status: "paid",
    lien_waiver_status: "final",
    created_at: "2025-07-10T10:00:00Z",
  },
  {
    id: "po-004",
    po_number: "PO-2025-0180",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Plumbing - Rough",
    vendor_name: "Masters Plumbing Inc",
    description: "Rough-in plumbing - all fixtures",
    amount: 9800,
    retainage_percent: 5,
    retainage_amount: 490,
    net_amount: 9310,
    status: "approved",
    lien_waiver_status: "partial",
    created_at: "2025-08-01T10:00:00Z",
  },
  {
    id: "po-005",
    po_number: "PO-2025-0181",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Electrical - Rough",
    vendor_name: "Volt Electric Services",
    description: "Rough electrical - panel, circuits, boxes",
    amount: 11200,
    retainage_percent: 5,
    retainage_amount: 560,
    net_amount: 10640,
    status: "approved",
    lien_waiver_status: "partial",
    created_at: "2025-08-05T10:00:00Z",
  },
  {
    id: "po-006",
    po_number: "PO-2025-0199",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Insulation",
    vendor_name: "Southern Insulation Co",
    description: "Spray foam + batt insulation",
    amount: 6500,
    retainage_percent: 5,
    retainage_amount: 325,
    net_amount: 6175,
    status: "work_complete",
    lien_waiver_status: "not_received",
    created_at: "2025-09-01T10:00:00Z",
  },
  {
    id: "po-007",
    po_number: "PO-2025-0215",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Drywall - Hang",
    vendor_name: "Pro Drywall Solutions",
    description: "Drywall hanging - all interior",
    amount: 8900,
    retainage_percent: 5,
    retainage_amount: 445,
    net_amount: 8455,
    status: "invoiced",
    lien_waiver_status: "not_received",
    invoice_number: "INV-4821",
    invoice_date: "2026-01-15",
    created_at: "2025-10-01T10:00:00Z",
  },
  {
    id: "po-008",
    po_number: "PO-2025-0216",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Drywall - Finish",
    vendor_name: "Pro Drywall Solutions",
    description: "Drywall finishing, texture, and sanding",
    amount: 7200,
    retainage_percent: 5,
    retainage_amount: 360,
    net_amount: 6840,
    status: "issued",
    lien_waiver_status: "not_received",
    created_at: "2025-10-05T10:00:00Z",
  },
  {
    id: "po-009",
    po_number: "PO-2025-0230",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Interior Trim - Material",
    vendor_name: "Carolina Lumber Supply",
    description: "Trim package - baseboard, casing, crown",
    amount: 5400,
    retainage_percent: 0,
    retainage_amount: 0,
    net_amount: 5400,
    status: "draft",
    lien_waiver_status: "not_received",
    created_at: "2026-01-20T10:00:00Z",
  },
  {
    id: "po-010",
    po_number: "PO-2025-0231",
    unit_id: "unit-001-007",
    job_id: "job-001",
    trade_category: "Cabinets",
    vendor_name: "Heritage Cabinet Co",
    description: "Kitchen & bath cabinetry - Shaker style",
    amount: 14500,
    retainage_percent: 0,
    retainage_amount: 0,
    net_amount: 14500,
    status: "draft",
    lien_waiver_status: "not_received",
    created_at: "2026-01-22T10:00:00Z",
  },
]

// ---- Change Orders ----
export const MOCK_CHANGE_ORDERS: ChangeOrder[] = [
  {
    id: "co-001",
    co_number: "CO-001",
    job_id: "job-001",
    unit_id: "unit-001-007",
    unit_number: "MC2-007",
    description: "Owner requested upgraded kitchen appliance package",
    reason: "owner_request",
    cost_impact: 4200,
    markup_percent: 30,
    total_amount: 5460,
    schedule_impact_days: 0,
    status: "approved",
    submitted_by: "Mike Thompson",
    submitted_date: "2025-11-15",
    reviewed_by: "Sarah Chen",
    reviewed_date: "2025-11-18",
  },
  {
    id: "co-002",
    co_number: "CO-002",
    job_id: "job-001",
    unit_id: "unit-001-009",
    unit_number: "MC2-009",
    description: "Rock encountered during foundation excavation - additional removal",
    reason: "field_condition",
    cost_impact: 3800,
    markup_percent: 10,
    total_amount: 4180,
    schedule_impact_days: 3,
    status: "approved",
    submitted_by: "Mike Thompson",
    submitted_date: "2025-08-22",
    reviewed_by: "Sarah Chen",
    reviewed_date: "2025-08-23",
  },
  {
    id: "co-003",
    co_number: "CO-003",
    job_id: "job-001",
    unit_id: "unit-001-012",
    unit_number: "MC2-012",
    description: "Electrical panel location change per updated code requirement",
    reason: "code_requirement",
    cost_impact: 1200,
    markup_percent: 0,
    total_amount: 1200,
    schedule_impact_days: 1,
    status: "revised",
    submitted_by: "Dave Rodriguez",
    submitted_date: "2026-02-10",
  },
  {
    id: "co-004",
    co_number: "CO-004",
    job_id: "job-001",
    unit_id: "unit-001-007",
    unit_number: "MC2-007",
    description: "Upgraded countertop from granite to quartzite",
    reason: "owner_request",
    cost_impact: 2800,
    markup_percent: 30,
    total_amount: 3640,
    schedule_impact_days: 5,
    status: "pending",
    submitted_by: "Mike Thompson",
    submitted_date: "2026-02-14",
  },
  {
    id: "co-005",
    co_number: "CO-005",
    job_id: "job-001",
    unit_id: "unit-001-015",
    unit_number: "MC2-015",
    description: "Foundation design error - footer depth insufficient per geotech",
    reason: "design_error",
    cost_impact: 5600,
    markup_percent: 0,
    total_amount: 5600,
    schedule_impact_days: 7,
    status: "approved",
    submitted_by: "Mike Thompson",
    submitted_date: "2025-12-01",
    reviewed_by: "Sarah Chen",
    reviewed_date: "2025-12-03",
  },
]

// ---- Selections ----
export const MOCK_SELECTIONS: Selection[] = [
  {
    id: "sel-001",
    unit_id: "unit-001-007",
    category: "Cabinets",
    item_name: "Shaker White - Full Overlay",
    description: "42\" uppers, soft-close, dovetail drawers",
    vendor: "Heritage Cabinet Co",
    base_cost: 12000,
    upgrade_delta: 2500,
    status: "ordered",
    linked_po_id: "po-010",
  },
  {
    id: "sel-002",
    unit_id: "unit-001-007",
    category: "Countertops",
    item_name: "Calacatta Quartzite",
    description: "3cm slab, eased edge, undermount sink cutout",
    vendor: "Stone Center of SC",
    base_cost: 4500,
    upgrade_delta: 2800,
    status: "selected",
  },
  {
    id: "sel-003",
    unit_id: "unit-001-007",
    category: "Flooring",
    item_name: "Hickory Engineered Hardwood",
    description: '5" plank, natural finish, tongue & groove',
    vendor: "Floor & Decor",
    base_cost: 8200,
    upgrade_delta: 1800,
    status: "ordered",
  },
  {
    id: "sel-004",
    unit_id: "unit-001-007",
    category: "Paint Interior",
    item_name: "Sherwin-Williams Accessible Beige",
    description: "SW 7036, eggshell finish throughout, semi-gloss trim",
    vendor: "Sherwin-Williams",
    base_cost: 3200,
    upgrade_delta: 0,
    status: "installed",
  },
  {
    id: "sel-005",
    unit_id: "unit-001-007",
    category: "Plumbing Fixtures",
    item_name: "Kohler Artifacts Collection",
    description: "Kitchen faucet, bath faucets (3), shower valves (2)",
    vendor: "Ferguson Supply",
    base_cost: 2800,
    upgrade_delta: 1200,
    status: "received",
  },
  {
    id: "sel-006",
    unit_id: "unit-001-007",
    category: "Lighting",
    item_name: "Standard Package + Dining Chandelier Upgrade",
    description: "LED recessed throughout, pendant kitchen island, chandelier dining",
    vendor: "Lighting Direct",
    base_cost: 3500,
    upgrade_delta: 950,
    status: "selected",
  },
  {
    id: "sel-007",
    unit_id: "unit-001-007",
    category: "Appliances",
    item_name: "KitchenAid Professional Series",
    description: "Refrigerator, range, dishwasher, microwave, hood vent",
    vendor: "Ferguson Supply",
    base_cost: 5500,
    upgrade_delta: 4200,
    status: "ordered",
  },
  {
    id: "sel-008",
    unit_id: "unit-001-007",
    category: "Hardware",
    item_name: "Brushed Brass Modern Collection",
    description: "Cabinet pulls, knobs, bath hardware",
    vendor: "Build.com",
    base_cost: 800,
    upgrade_delta: 350,
    status: "pending",
  },
  {
    id: "sel-009",
    unit_id: "unit-001-007",
    category: "Shower Doors",
    item_name: "Frameless Glass Enclosure",
    description: '3/8" clear glass, brushed brass hardware',
    vendor: "Greenville Glass Works",
    base_cost: 1800,
    upgrade_delta: 600,
    status: "pending",
  },
  {
    id: "sel-010",
    unit_id: "unit-001-007",
    category: "Mirrors",
    item_name: "Frameless Beveled Mirrors",
    description: "Master bath 48x36, hall bath 36x30, powder 24x30",
    vendor: "Greenville Glass Works",
    base_cost: 650,
    upgrade_delta: 0,
    status: "pending",
  },
]

// ---- Vendors ----
export const MOCK_VENDORS: Vendor[] = [
  {
    id: "vendor-001",
    company_name: "Precision Framing LLC",
    contact_name: "Roberto Hernandez",
    email: "roberto@precisionframing.com",
    phone: "(864) 555-0101",
    trades: ["Framing - Labor", "Framing - Lumber Material"],
    license_number: "SC-RBC-45892",
    license_expiration: "2026-12-31",
    insurance_certificates: [
      {
        id: "cert-001",
        type: "General Liability",
        carrier: "State Farm",
        policy_number: "GL-894521",
        expiration_date: "2026-06-30",
        coverage_amount: 2000000,
      },
      {
        id: "cert-002",
        type: "Workers Compensation",
        carrier: "Hartford",
        policy_number: "WC-331205",
        expiration_date: "2026-06-30",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.7,
    ytd_payments: 245800,
    payment_info_masked: "****1234",
    status: "active",
  },
  {
    id: "vendor-002",
    company_name: "Masters Plumbing Inc",
    contact_name: "James Masters",
    email: "james@mastersplumbing.com",
    phone: "(864) 555-0202",
    trades: ["Plumbing - Rough", "Plumbing - Finish"],
    license_number: "SC-MP-78234",
    license_expiration: "2026-09-30",
    insurance_certificates: [
      {
        id: "cert-003",
        type: "General Liability",
        carrier: "Progressive",
        policy_number: "GL-445678",
        expiration_date: "2026-03-15",
        coverage_amount: 2000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.3,
    ytd_payments: 187600,
    payment_info_masked: "****5678",
    status: "active",
  },
  {
    id: "vendor-003",
    company_name: "Volt Electric Services",
    contact_name: "Kevin Watts",
    email: "kevin@voltelectric.com",
    phone: "(864) 555-0303",
    trades: ["Electrical - Rough", "Electrical - Finish", "Low Voltage/Smart Home"],
    license_number: "SC-EC-55612",
    license_expiration: "2026-11-30",
    insurance_certificates: [
      {
        id: "cert-004",
        type: "General Liability",
        carrier: "Nationwide",
        policy_number: "GL-998877",
        expiration_date: "2026-08-31",
        coverage_amount: 2000000,
      },
      {
        id: "cert-005",
        type: "Workers Compensation",
        carrier: "Nationwide",
        policy_number: "WC-998878",
        expiration_date: "2026-08-31",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.8,
    ytd_payments: 212400,
    payment_info_masked: "****9012",
    status: "active",
  },
  {
    id: "vendor-004",
    company_name: "Summit Roofing Co",
    contact_name: "Paul Summit",
    email: "paul@summitroofing.com",
    phone: "(864) 555-0404",
    trades: ["Roofing", "Gutters & Downspouts"],
    license_number: "SC-RC-33445",
    license_expiration: "2026-06-30",
    insurance_certificates: [
      {
        id: "cert-006",
        type: "General Liability",
        carrier: "USAA",
        policy_number: "GL-112233",
        expiration_date: "2026-04-01",
        coverage_amount: 3000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.5,
    ytd_payments: 156200,
    payment_info_masked: "****3456",
    status: "active",
  },
  {
    id: "vendor-005",
    company_name: "Pro Drywall Solutions",
    contact_name: "Tony Ramirez",
    email: "tony@prodrywall.com",
    phone: "(864) 555-0505",
    trades: ["Drywall - Hang", "Drywall - Finish"],
    license_number: "SC-GC-66789",
    license_expiration: "2026-05-31",
    insurance_certificates: [
      {
        id: "cert-007",
        type: "General Liability",
        carrier: "Liberty Mutual",
        policy_number: "GL-556677",
        expiration_date: "2026-02-28",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.1,
    ytd_payments: 134800,
    payment_info_masked: "****7890",
    status: "active",
  },
  {
    id: "vendor-006",
    company_name: "Southern Insulation Co",
    contact_name: "Mark Davis",
    email: "mark@southerninsulation.com",
    phone: "(864) 555-0606",
    trades: ["Insulation"],
    license_number: "SC-IC-22334",
    license_expiration: "2026-10-31",
    insurance_certificates: [
      {
        id: "cert-008",
        type: "General Liability",
        carrier: "Travelers",
        policy_number: "GL-889900",
        expiration_date: "2026-07-15",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.4,
    ytd_payments: 89400,
    payment_info_masked: "****2345",
    status: "active",
  },
  {
    id: "vendor-007",
    company_name: "Carolina Lumber Supply",
    contact_name: "Bill Johnson",
    email: "bill@carolinalumber.com",
    phone: "(864) 555-0707",
    trades: ["Framing - Lumber Material", "Interior Trim - Material"],
    license_number: "N/A",
    license_expiration: undefined,
    insurance_certificates: [],
    w9_status: "received",
    performance_score: 4.6,
    ytd_payments: 342100,
    payment_info_masked: "****6789",
    notes: "Material supplier - no trade license required",
    status: "active",
  },
  {
    id: "vendor-008",
    company_name: "Heritage Cabinet Co",
    contact_name: "Linda Chen",
    email: "linda@heritagecabinets.com",
    phone: "(864) 555-0808",
    trades: ["Cabinets"],
    license_number: "SC-GC-44556",
    license_expiration: "2027-03-31",
    insurance_certificates: [
      {
        id: "cert-009",
        type: "General Liability",
        carrier: "Erie Insurance",
        policy_number: "GL-334455",
        expiration_date: "2026-09-30",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.9,
    ytd_payments: 178500,
    payment_info_masked: "****0123",
    status: "active",
  },
  {
    id: "vendor-009",
    company_name: "Greenville HVAC Pros",
    contact_name: "Steve Miller",
    email: "steve@gvilleHVAC.com",
    phone: "(864) 555-0909",
    trades: ["HVAC - Rough", "HVAC - Finish"],
    license_number: "SC-MEC-77889",
    license_expiration: "2026-12-31",
    insurance_certificates: [
      {
        id: "cert-010",
        type: "General Liability",
        carrier: "State Farm",
        policy_number: "GL-778899",
        expiration_date: "2026-05-15",
        coverage_amount: 2000000,
      },
    ],
    w9_status: "pending",
    performance_score: 3.9,
    ytd_payments: 198700,
    payment_info_masked: "****4567",
    status: "active",
  },
  {
    id: "vendor-010",
    company_name: "Tri-County Concrete",
    contact_name: "Frank Morales",
    email: "frank@tricountyconcrete.com",
    phone: "(864) 555-1010",
    trades: ["Concrete - Foundation", "Concrete - Flatwork", "Concrete - Porch/Steps"],
    license_number: "SC-GC-11223",
    license_expiration: "2025-12-31",
    insurance_certificates: [
      {
        id: "cert-011",
        type: "General Liability",
        carrier: "Hartford",
        policy_number: "GL-001122",
        expiration_date: "2025-11-30",
        coverage_amount: 1000000,
      },
    ],
    w9_status: "received",
    performance_score: 4.2,
    ytd_payments: 267900,
    payment_info_masked: "****8901",
    status: "active",
  },
]

// ---- Warranty Claims ----
export const MOCK_WARRANTY_CLAIMS: WarrantyClaim[] = [
  {
    id: "wc-001",
    claim_number: "WC-2026-001",
    unit_id: "unit-001-001",
    unit_address: "101 Millbrook Crossing Dr",
    reported_date: "2026-01-15",
    category: "Plumbing",
    description: "Slow drain in master bathroom shower. Possible hair/debris blockage or improper slope.",
    urgency: "routine",
    status: "scheduled",
    vendor_id: "vendor-002",
    vendor_name: "Masters Plumbing Inc",
    cost: 250,
    owner_signoff: false,
  },
  {
    id: "wc-002",
    claim_number: "WC-2026-002",
    unit_id: "unit-001-002",
    unit_address: "102 Millbrook Crossing Dr",
    reported_date: "2026-01-20",
    category: "HVAC",
    description: "Upstairs bedrooms not reaching set temperature. Ductwork may need balancing.",
    urgency: "urgent",
    status: "in_progress",
    vendor_id: "vendor-009",
    vendor_name: "Greenville HVAC Pros",
    cost: 450,
    owner_signoff: false,
  },
  {
    id: "wc-003",
    claim_number: "WC-2026-003",
    unit_id: "unit-001-003",
    unit_address: "103 Millbrook Crossing Dr",
    reported_date: "2026-02-01",
    category: "Drywall",
    description: "Nail pops appearing in living room ceiling and master bedroom walls.",
    urgency: "routine",
    status: "open",
    vendor_id: "vendor-005",
    vendor_name: "Pro Drywall Solutions",
    cost: 0,
    owner_signoff: false,
  },
  {
    id: "wc-004",
    claim_number: "WC-2026-004",
    unit_id: "unit-001-004",
    unit_address: "104 Millbrook Crossing Dr",
    reported_date: "2026-02-05",
    category: "Roofing",
    description: "Water stain appearing on second floor ceiling after heavy rain. Possible flashing issue.",
    urgency: "emergency",
    status: "in_progress",
    vendor_id: "vendor-004",
    vendor_name: "Summit Roofing Co",
    cost: 1200,
    owner_signoff: false,
  },
  {
    id: "wc-005",
    claim_number: "WC-2026-005",
    unit_id: "unit-001-001",
    unit_address: "101 Millbrook Crossing Dr",
    reported_date: "2025-12-10",
    category: "Exterior",
    description: "Grading issue causing water to pool near foundation on north side.",
    urgency: "urgent",
    status: "resolved",
    vendor_name: "Site Work Pros",
    cost: 800,
    resolution_notes: "Re-graded north side, added French drain. Verified drainage after rain event.",
    resolved_date: "2025-12-28",
    owner_signoff: true,
  },
  {
    id: "wc-006",
    claim_number: "WC-2025-042",
    unit_id: "unit-001-005",
    unit_address: "105 Millbrook Crossing Dr",
    reported_date: "2025-11-15",
    category: "Electrical",
    description: "GFCI outlet in kitchen tripping intermittently.",
    urgency: "routine",
    status: "closed",
    vendor_id: "vendor-003",
    vendor_name: "Volt Electric Services",
    cost: 175,
    resolution_notes: "Replaced defective GFCI outlet. Tested all circuits. No further issues.",
    resolved_date: "2025-11-22",
    owner_signoff: true,
  },
]

// ---- Activity Feed ----
export const MOCK_ACTIVITY_FEED: ActivityFeedItem[] = [
  {
    id: "act-001",
    timestamp: "2026-02-17T09:30:00Z",
    type: "milestone",
    message: "MC2-007 advanced to Phase 10: Interior Trim",
    user: "Mike Thompson",
    unit_number: "MC2-007",
  },
  {
    id: "act-002",
    timestamp: "2026-02-16T16:00:00Z",
    type: "inspection",
    message: "MC2-012 Insulation inspection passed",
    user: "Greenville County",
    unit_number: "MC2-012",
  },
  {
    id: "act-003",
    timestamp: "2026-02-16T14:30:00Z",
    type: "po",
    message: "PO-2025-0215 invoice entered for Pro Drywall Solutions ($8,900)",
    user: "Sarah Chen",
    unit_number: "MC2-007",
  },
  {
    id: "act-004",
    timestamp: "2026-02-15T11:00:00Z",
    type: "change_order",
    message: "CO-004 submitted: Upgraded countertop for MC2-007 ($3,640)",
    user: "Mike Thompson",
    unit_number: "MC2-007",
  },
  {
    id: "act-005",
    timestamp: "2026-02-14T10:00:00Z",
    type: "po",
    message: "PO-2025-0231 created for Heritage Cabinet Co (Cabinets - $14,500)",
    user: "Sarah Chen",
    unit_number: "MC2-007",
  },
  {
    id: "act-006",
    timestamp: "2026-02-13T15:30:00Z",
    type: "milestone",
    message: "MC2-013 advanced to Phase 6: Roofing",
    user: "Mike Thompson",
    unit_number: "MC2-013",
  },
  {
    id: "act-007",
    timestamp: "2026-02-12T09:00:00Z",
    type: "inspection",
    message: "MC2-009 Framing inspection passed",
    user: "Greenville County",
    unit_number: "MC2-009",
  },
  {
    id: "act-008",
    timestamp: "2026-02-11T14:00:00Z",
    type: "general",
    message: "Weekly superintendent walkthrough completed for Millbrook Phase 2",
    user: "Mike Thompson",
  },
]

// ============================================================================
// AP/AR Mock Data for Construction Accounting
// ============================================================================

import type {
  APInvoice,
  APPayment,
  ARInvoice,
  RetainageEntry,
  DrawScheduleItem,
  JobCostReport,
  Vendor1099Summary,
} from "./accounting-types"

export const MOCK_AP_INVOICES: APInvoice[] = [
  {
    id: "inv-001",
    organization_id: "org-001",
    invoice_number: "INV-2026-0001",
    vendor_contact_id: "vendor-001",
    po_id: "po-001",
    job_id: "job-001",
    unit_id: "unit-001",
    invoice_date: "2026-01-15",
    due_date: "2026-02-14",
    received_date: "2026-01-16",
    gross_amount: 45000,
    retainage_held: 4500,
    net_amount: 40500,
    amount_paid: 0,
    balance_due: 40500,
    description: "Foundation concrete and forming - MC2-001",
    cost_code: "foundation",
    status: "approved",
    approved_by: null,
    approved_at: "2026-01-20T10:00:00Z",
    accounting_period: "2026-01",
    supporting_document_id: null,
    created_at: "2026-01-16T09:00:00Z",
    updated_at: "2026-01-20T10:00:00Z",
    vendor: { id: "vendor-001", company_name: "Palmetto Concrete LLC" },
    po: { id: "po-001", po_number: "PO-2026-0001", amount: 48000 },
    job: { id: "job-001", name: "Millbrook Crossing Phase 2" },
    unit: { id: "unit-001", unit_number: "MC2-001" },
    aging_days: 3,
    aging_bucket: "current",
  },
  {
    id: "inv-002",
    organization_id: "org-001",
    invoice_number: "INV-2026-0002",
    vendor_contact_id: "vendor-002",
    po_id: "po-003",
    job_id: "job-001",
    unit_id: "unit-002",
    invoice_date: "2026-01-10",
    due_date: "2026-02-09",
    received_date: "2026-01-11",
    gross_amount: 62000,
    retainage_held: 6200,
    net_amount: 55800,
    amount_paid: 55800,
    balance_due: 0,
    description: "Framing package - MC2-002",
    cost_code: "framing",
    status: "paid",
    approved_by: null,
    approved_at: "2026-01-15T14:00:00Z",
    accounting_period: "2026-01",
    supporting_document_id: null,
    created_at: "2026-01-11T08:00:00Z",
    updated_at: "2026-02-01T09:00:00Z",
    vendor: { id: "vendor-002", company_name: "Carolina Framing Co" },
    po: { id: "po-003", po_number: "PO-2026-0003", amount: 65000 },
    job: { id: "job-001", name: "Millbrook Crossing Phase 2" },
    unit: { id: "unit-002", unit_number: "MC2-002" },
    aging_days: 0,
    aging_bucket: "current",
  },
  {
    id: "inv-003",
    organization_id: "org-001",
    invoice_number: "INV-2026-0003",
    vendor_contact_id: "vendor-003",
    po_id: null,
    job_id: "job-001",
    unit_id: null,
    invoice_date: "2025-12-01",
    due_date: "2025-12-31",
    received_date: "2025-12-02",
    gross_amount: 18500,
    retainage_held: 0,
    net_amount: 18500,
    amount_paid: 0,
    balance_due: 18500,
    description: "Job-site portable restrooms - Monthly",
    cost_code: "general_conditions",
    status: "disputed",
    approved_by: null,
    approved_at: null,
    accounting_period: "2025-12",
    supporting_document_id: null,
    created_at: "2025-12-02T10:00:00Z",
    updated_at: "2025-12-15T10:00:00Z",
    vendor: { id: "vendor-003", company_name: "All-Site Services Inc" },
    job: { id: "job-001", name: "Millbrook Crossing Phase 2" },
    aging_days: 48,
    aging_bucket: "31-60",
  },
  {
    id: "inv-004",
    organization_id: "org-001",
    invoice_number: "INV-2026-0004",
    vendor_contact_id: "vendor-004",
    po_id: "po-005",
    job_id: "job-002",
    unit_id: "unit-010",
    invoice_date: "2026-02-01",
    due_date: "2026-03-03",
    received_date: "2026-02-02",
    gross_amount: 28750,
    retainage_held: 2875,
    net_amount: 25875,
    amount_paid: 0,
    balance_due: 25875,
    description: "Electrical rough-in - OE-001",
    cost_code: "electrical",
    status: "received",
    approved_by: null,
    approved_at: null,
    accounting_period: "2026-02",
    supporting_document_id: null,
    created_at: "2026-02-02T08:00:00Z",
    updated_at: "2026-02-02T08:00:00Z",
    vendor: { id: "vendor-004", company_name: "Upstate Electric LLC" },
    po: { id: "po-005", po_number: "PO-2026-0005", amount: 30000 },
    job: { id: "job-002", name: "Oakridge Estates" },
    unit: { id: "unit-010", unit_number: "OE-001" },
    aging_days: 0,
    aging_bucket: "current",
  },
]

export const MOCK_AP_PAYMENTS: APPayment[] = [
  {
    id: "pay-001",
    organization_id: "org-001",
    payment_number: "PAY-2026-0001",
    payment_date: "2026-02-01",
    payment_method: "check",
    payment_reference: "CHK-10234",
    vendor_contact_id: "vendor-002",
    total_amount: 55800,
    bank_account: "Operating - First Citizens",
    batch_id: "batch-001",
    status: "cleared",
    voided_date: null,
    voided_reason: null,
    created_by: null,
    created_at: "2026-02-01T09:00:00Z",
    updated_at: "2026-02-05T14:00:00Z",
    vendor: { id: "vendor-002", company_name: "Carolina Framing Co" },
    applications: [
      {
        id: "pa-001",
        payment_id: "pay-001",
        invoice_id: "inv-002",
        amount_applied: 55800,
        is_retainage_release: false,
        created_at: "2026-02-01T09:00:00Z",
      },
    ],
  },
]

export const MOCK_DRAW_SCHEDULE: DrawScheduleItem[] = [
  {
    id: "draw-001",
    job_id: "job-001",
    draw_number: 1,
    name: "Deposit",
    percentage: 20,
    amount: 1750000,
    milestone_phase: null,
    status: "paid",
    requested_date: "2025-10-01",
    approved_date: "2025-10-05",
    invoice_id: "ar-001",
    paid_date: "2025-10-15",
    notes: null,
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2025-10-15T09:00:00Z",
  },
  {
    id: "draw-002",
    job_id: "job-001",
    draw_number: 2,
    name: "Foundation",
    percentage: 20,
    amount: 1750000,
    milestone_phase: 4,
    status: "requested",
    requested_date: "2026-02-10",
    approved_date: null,
    invoice_id: null,
    paid_date: null,
    notes: "Foundation complete on 12 units",
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2026-02-10T09:00:00Z",
  },
  {
    id: "draw-003",
    job_id: "job-001",
    draw_number: 3,
    name: "Framing / Dry-In",
    percentage: 25,
    amount: 2187500,
    milestone_phase: 5,
    status: "pending",
    requested_date: null,
    approved_date: null,
    invoice_id: null,
    paid_date: null,
    notes: null,
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2025-09-15T09:00:00Z",
  },
  {
    id: "draw-004",
    job_id: "job-001",
    draw_number: 4,
    name: "Drywall / Trim",
    percentage: 25,
    amount: 2187500,
    milestone_phase: 10,
    status: "pending",
    requested_date: null,
    approved_date: null,
    invoice_id: null,
    paid_date: null,
    notes: null,
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2025-09-15T09:00:00Z",
  },
  {
    id: "draw-005",
    job_id: "job-001",
    draw_number: 5,
    name: "Final / CO",
    percentage: 10,
    amount: 875000,
    milestone_phase: 16,
    status: "pending",
    requested_date: null,
    approved_date: null,
    invoice_id: null,
    paid_date: null,
    notes: "Adjusted for change orders and unused contingency",
    created_at: "2025-09-15T09:00:00Z",
    updated_at: "2025-09-15T09:00:00Z",
  },
]

export const MOCK_RETAINAGE: RetainageEntry[] = [
  {
    id: "ret-001",
    organization_id: "org-001",
    job_id: "job-001",
    unit_id: "unit-002",
    vendor_contact_id: "vendor-002",
    po_id: "po-003",
    invoice_id: "inv-002",
    amount_held: 6200,
    amount_released: 0,
    release_date: null,
    release_payment_id: null,
    lien_waiver_status: "conditional",
    status: "held",
    created_at: "2026-01-11T08:00:00Z",
    vendor: { id: "vendor-002", company_name: "Carolina Framing Co" },
    po: { id: "po-003", po_number: "PO-2026-0003" },
  },
  {
    id: "ret-002",
    organization_id: "org-001",
    job_id: "job-001",
    unit_id: "unit-001",
    vendor_contact_id: "vendor-001",
    po_id: "po-001",
    invoice_id: "inv-001",
    amount_held: 4500,
    amount_released: 0,
    release_date: null,
    release_payment_id: null,
    lien_waiver_status: "not_received",
    status: "held",
    created_at: "2026-01-16T09:00:00Z",
    vendor: { id: "vendor-001", company_name: "Palmetto Concrete LLC" },
    po: { id: "po-001", po_number: "PO-2026-0001" },
  },
]

export const MOCK_JOB_COST_REPORT: JobCostReport = {
  job_id: "job-001",
  job_name: "Millbrook Crossing Phase 2",
  contract_amount: 8750000,
  builder_fee: 612500,
  job_total_budget: 8137500,
  job_total_committed: 5250000,
  job_total_actual: 2890000,
  job_total_projected: 5350000,
  job_total_variance: 2787500,
  units: [
    {
      unit_id: "unit-001",
      unit_number: "MC2-001",
      total_budget: 339062,
      total_committed: 218750,
      total_actual: 120416,
      total_projected: 223125,
      total_variance: 115937,
      lines: [
        { cost_code: "site_work", cost_code_name: "Site Work", budget: 22000, committed: 21500, actual: 21500, projected_final: 21500, variance: 500, pct_complete: 100 },
        { cost_code: "foundation", cost_code_name: "Foundation", budget: 48000, committed: 48000, actual: 45000, projected_final: 48000, variance: 0, pct_complete: 93.75 },
        { cost_code: "framing", cost_code_name: "Framing", budget: 65000, committed: 62000, actual: 0, projected_final: 62000, variance: 3000, pct_complete: 0 },
        { cost_code: "roofing", cost_code_name: "Roofing", budget: 18000, committed: 17500, actual: 0, projected_final: 17500, variance: 500, pct_complete: 0 },
        { cost_code: "plumbing", cost_code_name: "Plumbing", budget: 28000, committed: 27500, actual: 27500, projected_final: 27500, variance: 500, pct_complete: 100 },
        { cost_code: "electrical", cost_code_name: "Electrical", budget: 30000, committed: 0, actual: 0, projected_final: 0, variance: 30000, pct_complete: 0 },
        { cost_code: "hvac", cost_code_name: "HVAC", budget: 24000, committed: 0, actual: 0, projected_final: 0, variance: 24000, pct_complete: 0 },
        { cost_code: "insulation", cost_code_name: "Insulation", budget: 8500, committed: 0, actual: 0, projected_final: 0, variance: 8500, pct_complete: 0 },
        { cost_code: "drywall", cost_code_name: "Drywall", budget: 22000, committed: 0, actual: 0, projected_final: 0, variance: 22000, pct_complete: 0 },
        { cost_code: "paint", cost_code_name: "Paint & Flooring", budget: 18000, committed: 0, actual: 0, projected_final: 0, variance: 18000, pct_complete: 0 },
        { cost_code: "cabinets", cost_code_name: "Cabinets & Countertops", budget: 16562, committed: 15250, actual: 0, projected_final: 15250, variance: 1312, pct_complete: 0 },
        { cost_code: "trim", cost_code_name: "Interior Trim", budget: 12000, committed: 0, actual: 0, projected_final: 0, variance: 12000, pct_complete: 0 },
        { cost_code: "exterior", cost_code_name: "Exterior Finish", budget: 15000, committed: 14500, actual: 14416, projected_final: 14500, variance: 500, pct_complete: 96.11 },
        { cost_code: "appliances", cost_code_name: "Appliances", budget: 8500, committed: 8500, actual: 8500, projected_final: 8500, variance: 0, pct_complete: 100 },
        { cost_code: "landscaping", cost_code_name: "Landscaping", budget: 5500, committed: 4000, actual: 3500, projected_final: 4375, variance: 1125, pct_complete: 63.64 },
      ],
    },
  ],
}

export const MOCK_1099_SUMMARIES: Vendor1099Summary[] = [
  { contact_id: "vendor-001", company_name: "Palmetto Concrete LLC", w9_on_file: true, tax_year: 2026, total_payments: 145000, is_1099_eligible: true },
  { contact_id: "vendor-002", company_name: "Carolina Framing Co", w9_on_file: true, tax_year: 2026, total_payments: 210000, is_1099_eligible: true },
  { contact_id: "vendor-003", company_name: "All-Site Services Inc", w9_on_file: false, tax_year: 2026, total_payments: 37000, is_1099_eligible: true },
  { contact_id: "vendor-004", company_name: "Upstate Electric LLC", w9_on_file: true, tax_year: 2026, total_payments: 89000, is_1099_eligible: true },
  { contact_id: "vendor-005", company_name: "Low Country Plumbing", w9_on_file: true, tax_year: 2026, total_payments: 420, is_1099_eligible: false },
]
